services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/files/:/usr/share/nginx/html
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.1-fpm
    volumes:
      - ./php/files:/usr/share/nginx/html

  bind9:
    image: internetsystemsconsortium/bind9:9.18
    restart: always
    ports:
      - "5354:53/udp"
      - "5354:53/tcp"
      - "127.0.0.1:953:953/tcp"
    volumes:
      - ./bind/etc/bind:/etc/bind
      - ./bind/var/cache/bind:/var/cache/bind
      - ./bind/var/lib/bind:/var/lib/bind
      - ./bind/var/log:/var/log

